#!/bin/bash
sudo=""
if [[ "$USER" != "root" ]]; then
    sudo="sudo"
fi

set -e
set -x
${sudo} apt-get update
${sudo} apt-get upgrade -y
${sudo} apt-get autoremove -y
${sudo} apt-get autoclean
${sudo} snap refresh
