#!/bin/bash
sudo=""
if [[ "$USER" != "root" ]]; then
    sudo="sudo"
fi

set -e
set -x
${sudo} apt-get update
${sudo} apt-get -y upgrade
${sudo} apt-get autoremove
${sudo} apt-get autoclean
${sudo} snap refresh
